# Generated by Django 5.0.1 on 2024-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='habit',
            name='clear_judge',
            field=models.CharField(default='None', max_length=256),
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(default='習慣に関する説明が入ります'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_include_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_require_elapsedtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='schedule_routine',
            field=models.JSONField(default={}),
        ),
    ]
