# Generated by Django 5.0.1 on 2024-02-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('list_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('habit_id', models.IntegerField()),
                ('habit_name', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
