# Generated by Django 5.0.1 on 2024-02-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habit',
        ),
    ]
